---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-github
  namespace: paseo
spec:
  encryptedData:
    GH_TOKEN: AgAny76h0vL73z5YgrqeJBJdgb+WcOdITV6HAGBQuC//ia4TFs2pt3szdtrwzc4u0jkqijgGVRTJNuXDgIGQcDoAHvYPgV2A2aGwlM/SMerbaoaGELNLEj17K3+pAY5C132Y0ZkHtUuUJNieY7P8wpv5ElSsha71CJ52FXMc1Jdpt+T6PaxX63Z25Z8TTiXaQkAkWD8cY4BTK1V3nm7Wn138OJKr2q6iAxHrpvBOYlZefwsYplizbdjzia+Bb/8/rpHHB7sYFJPOqlA4j91sz4IxRNF9hqxjDPfq6uKF+ZOUJhWYNGGPkwekyBPQPDTg3qhHMh99fqvka48K1Tz0Fjnt1EOOmSBeVYLRdgHzR9XAaPFNbduqLYpLiI5sxnQM8iZakXmWrSJT2qW3/hcudiatQ+WKTT69W7gyM5FgklRPtdCLknMXeOTmroKDVxVdF4x94F6eC/dS0bWZf7WggHsoYUayxGJ8hHvjE41LE+labeBbsvVcctAjRSFFVUE/muDHM1EzWNWjWbtusuS/r78Urmnh1UT4l6sPNBpVJbKYGUGgqoBkAtkYtP//MLurR8ef0PsUHpXNyK040cUEzI1OkSI2QJn1EM+l4rat5V8pnV6GH4gzLDD/DQJd50P0wy3ajVV4sW5amR7iNXfVpW5PuS5Z5NmeDNkVjdpLH+sR2k3yKJ20dk5siCcNkye40eHNvnZbduqKPsxUWVmFgsnwqhAuhfHuj/gVrNZoDSAxmIOrqrqdO5h05qyAJCSJuv/sG3DlQAp4F8CXwvmuBBDwytlHTkpzS/S439gW3MGCmr6QDk6Wdttzyu4Pgbg=
  template:
    metadata:
      name: paseo-github
      namespace: paseo
