---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-auth
  namespace: paseo
spec:
  encryptedData:
    password: AgCAQQgttPGZHelCQqCvjAL+i3jGU9n18BAk9cyhQ4Ro4Xaf4TkaMQC0v8M8lutGl8dY9tSYDv1bwCHifW/E/42qF2k8PuZz65vmIv2wPxXRWgy9z3ArfVPQz4TCYNKEhQTIxnDzYLkl3WYr0QCgai8k99hTCDEkri8oV394NKH8mrC1BnizW16nquuiK5k1CUyzjbOhwQcXF5KJZu71s1CGr//MQBD/Ut/gOJ/EAW2ACXqIrV7Hrc2WWw2lQRmIbtpMHWHTpQ8b7j8PdLWjqFvktjaIbU7kHXTjFRw3Q6Gl2zyEiVf9SPAFoMHXaLrs76pnyllzs5fELyU+ZUeOqPIpsNK3a6pDHFeC0AXUyo+cNRfy9bLCgLs92JP77X5enVilZohKqVIOCVBzDro2qaeKyj8K2Oa1D160Al2CCogtsWXsWK40O+KXY8bcr9yoa3UkWqCB9lVsmxKbpIry8Gk0LF7yywowEekE6Q+uSG7kwINTFQqatMp3rzwih7Sks83c7va/f2/x6QubCiQIlbPbTaE0xKpO9FNctZVI7stV1QtSW/nGcVFBQMpBn+jSFE+x8ZylL9JeLqrp729WzWIWMG43mfdpq2MeIDdk7TT1Pze5e3V7ZUAxK8FlowCmXaJoR0TAZ+c6PNM/G1RfmUaYc61OiDuuM7rLVT9+78vT7EWrSMpSLD3Jw8aqPncerlEgDV3iUeONB7rt2j7C5uRLe7TeEOPk9FthBmay62WHheH2r581R3eSpdFtVX1XmTC//EYvsq9K1T5oAwZW3XeZ
  template:
    metadata:
      name: paseo-auth
      namespace: paseo
