---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-auth
  namespace: paseo
spec:
  encryptedData:
    password: AgBMIi6KgeHH2jWIeA+5N29yc2CV2UBLjYwPs3y4Fe1HP2lEBeomCY2Gi8WmirFpGSfOF+aA94Q2wz1p8XtfZ3HFELw6ZeRIH+OOpfMwcD9epTGtfvaEKsfW1hM564L89/F4ql+h9EkLCg+nuOEUlgVojF4OqUSsVDW9WXTk0basVAxfj/CZuIPteFB2VMd8eo5XLB8v4D3k9lnzEIpwGEyayOnc7CQKUSwZM35niNzhsSzYW+G2Ocx4zg0QKkjgPGhkx6yuyEwHpmtVl1j7vBWn0K3BEt6TTGsyFf4++ThEjHajknEBBNBM+7Qzxdt5ox+XO2Itfk41A+WhI3VuU4bTatxJHU6yB87DXCMO3e+x4ptHmhBUZj70BtCbcN8z9c0IniFAL+1WU8REua6HxauJO++Msl6rDehX2WW7gZGUWxIVjJXe/8FNxKu+T3iqMWNVPhSvTBNcaSlsNDEJDDIls+oiRB0Fvo5zdR6npW47tvNROTajb+gVOKgmy3mnlw1Itm8z0RtYZno+mCo01vqywJj3glxF1YBgGnIWngkw7ukfj+fz6muqGxkEs20/9Rgdb09lptCEY0Gz5PqVcCeiGScNudIp6AevVHm1EyZ8IVs3AIhnm1GbNG2aw8tUY/4OquHT5pKDXIvOwqz1jzC6U/d5hujIAUqhreXnnqZhqpyRplejqxyR22jLEio9yD8zRCj/K1H/kUof6vs9OvwQhM9lGCAXysgDQ7rb9Gwu3CFwQwYH4oppB8rovA==
  template:
    metadata:
      name: paseo-auth
      namespace: paseo
