---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secrets
  namespace: pgadmin
spec:
  encryptedData:
    email: AgA815V+P1J+5uAPrq/atfpbwaFmmi+OUYoDZz5XouFPkpD5U/340yNDhIEbEA/yWZpspcTeAfkafuRxor9ozbqYpz9/MVnHnmhR8FEFxUhg4L1/7joh7+PgOyrg5cHzZq8rUkHin08LJz5RjnBw/JHyBVDVcYVIdHFju5FTFcxO4RZOH1Ywi5zCqwfiwqEAzMFbIxWuMJ+VtZImpQIkx53li0fyFNELtElv6fuD7sfLfmkgjHKQn1I6gf/MB2kW3+NpfhrWPsD/2CPU5OevcBkuuM9hiHC9edJaVgPEqwhTk9G9jVWb0yHqmJDIW3b7ssHSZQnm9AsxjZgzlSsfW3mfUuJ7v3v4GJIKZx5wMN8Nr1v+Lbkc27ejPkmHlvpfzSrw4L6bd0mplvIkJgPRwjwMm+WqUUvXj34Cwlks9YjfSVm+IJt33I9wHkX7DUH+3LnW7+gMXFNdbe64S9UHBTFNJVBCNa7i1x00k+VZ4Vbza8a9SwFPzaeuQEYkRgKdAQePjW1f/CF7iZRX3dcSiHZXuEbXDoHfQv5SVLeOakqyNbbILXkiii5OoTGddIDKFV52la+kEYng6rMfCdLNQIHzdfvdHCRkwAwO/2urwRXucx4TWkVY5SOfitkogCccnPyssCjNB4ZkffQ87wkGMqnQ1TmMgB/zjC420HG3KP9zHJSaW6dzj9kjeHOLQmkEA3zpG0W9mn+y4plVHGkiJNkrz3wxB9CWmLQ=
    password: AgCO9M/fJNyueJkaQdQIMeRD0V7GcNtIr5roR25qCJHGHUjQCyE2b2i3qGlb954IeLAq+vOEcW1LfrFKZm/lS2O2CNj5FIeBNra5IRjCe07SWPMmq9iEtNOP1CP/MYSEtHgYySQ4eA2OAqsx90fq8SRRTn8Q9L7uuhe08mOzAiZl25IFQlOizelDyKByP4PP8xPFgqkfqW5Rgz9MLySUUGs+WmU2em7hELzaV/hYyL9+NISzvK+LKnyhPviZdOVT9LFOcM64bdGrCY7pmxCRmy4fSlLQMnkntcvMTt4jm6qE19KBptPKX/llyo5W1rNDOCForpnuc/drp5apo666HlupXNIPth8hzpZHjQ8w1Eisz0DU0oFCy1NmqkLHQjUJ49CbTPWmOQIP6PXYh2jAFtAdaRAt27dl54/SvNDpySV5PmGmK5/+vWe7wanKiR8BeOrHXN9xyRvmkBsM68O5Fh2HLQbfcyLsFSB3o+D+D8sweYBACrNFrEgjuUqJOHoRvKGr6pTbnbNJXin3x6mSyfbBSN0bzCQobt6jfAJPNTV7wzn6HtibbfMM0etGQjW0aOpUmqte3kn61pKZMmXGbCxiVR8gI+7GEgzHAiGtTUHj0TVqg8dKF1obO7cGX87SmCLnmXgQMfVZmsYst4dzhKMEe45NbyAsaeFt6njnmz9Rw20UTGWmdXRlaimF18+botrBGsLGzCqpkgna0hFYu02ibcNDQWCLxA==
  template:
    metadata:
      name: pgadmin-secrets
      namespace: pgadmin
    type: Opaque
