apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: hortusfox-db
spec:
  type: ClusterIP
  selector:
    app: hortusfox-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql
