apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: planka-ingress
  namespace: planka
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`todo.mauzlab.de`)
      services:
        - name: planka
          port: 1337
  tls: {}
