apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: planka

# Helm chart for Planka
helmCharts:
  - name: planka
    repo: https://plankanban.github.io/helm-chart
    version: 2.0.3
    releaseName: planka
    valuesFile: planka-values.yaml

resources:
  - postgres/sealed-secrets.yaml
  - ingress.yaml
