apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-shared
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: app
      owner: app

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"

  managed:
    roles:
      - name: pgadmin_admin
        ensure: present
        login: true
        createrole: true
        createdb: true
        passwordSecret:
          name: pgadmin-admin-db-secret

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: nas-s3-store
