---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-admin-db-secret
  namespace: databases
spec:
  encryptedData:
    password: AgBJvq45s6NBE3Rtz5GBG6f9SLobvO6MN88K9nZW9UkQVxmfJmOGJ2pb9KtfhYPoB1xX2GYqDemJzByr8Y/kDLqNTKxVCTnXNa3XxEmyxdJpT50YRa+bkOXkuM2+pS8kfez4TUvFjUfusXFLCbhqEmG5uY+NZ900qJMBYS243dKJTJi9fjqKlqP1jAhLjaccQyQJIwFbKoGBOAe2wgWrFLiGQjDCcSnZH84qavTbreolzo1GakialjOJDrAryrYPS7obW8AdsfLQXOkL4yL4qQ8d9MBcTXH8KXVjm7NhL8A07u6xX68hgquIWvJLwZw9yiLYYuO9cotPgcm+275EJHB5w68/NlZ4J11lNYKsXoKIPrmXt6IgpsFmU9Mm/0d6h3hxwPJk8jqkaJO3pDpU6XUiFrIAw7oV7Yz9/a022lXD3nG/fYl9isOVluLGE5A8PUPQ064FYDKX2yIKh05vkZZnWIbhVhFLRvHcfT71IQ5Y6CSxpSM6nWamxgim3Y2r5PPS2tia/iP4YLyRVMuNlqlouzdw1IZrMprV/uVxQPMW9yEYwBxA/s8mHaHCKf6rELuLHIg3NLVbPHYfGO4B6/m8YZzoEF/Pb2rOZYSnaJbyoWDjurEWIZtmsQT0S5JiqhejgenXMlcAVJOXgjNl3ZBzel5iCuUYprQcETqujBStG5EZ0KvZ/Q1N5xBVgb/vxXcYQzrWQV655lWDzp5wUGNvIOwtCtkui7Jia312KXZv+w==
    username: AgADVx5DCxv8XZoelnCXSR0JOF+gNsIfU2h7iv2zeUP3wIrfNRGYJwytbbFZOBLFPtdl4AZltY/Slr+LfpuL9QB2H2DL1Sc9IKGk7bSP6qjnTFM2+Ne6ZukV6CGevsdQNyeUeC+6OCDdFE4+3sg7cTbuFcqPQYtIPYYBxN3ph0vgfoie5FxXO5LGHSNOF1jyRUQW5W0bEsLQzTP4r+qPNIahoLpTOUnKFHTZd/vT0gKh/r9EJTJpmTCG6zDVNG8QnpeNGVQ/TCdcSM1E9amwlg2oJOv4rRPP+dGvBMBamXQCjQNV5HhiHImbkQEqjYttWKd2Ncos27Z4kq3656LE52S1RLORzU/dOUdwuP2GBuYr9d0/k7BXBYNZuBFprgbe0WB5JQnjEbNJ0WWDCPko6cZUM8/3dH6+TSJiK0POtvQCER8pqo8VjIVad0uKEgAPr2Ai+R26lbw+2PANkaAGo6eUHHIbqhU9uQ9Se9uH1uYKjij7OraHZZ/mIOrYerLXxTqhzdZaBuKzeDWPbmO8GGl4IQSTWxdJWdOqNdS+Sb663RQfTH3ZXh2kUEhmmpulk+xqeqPZ72eCGPl4itnUHY7w/kc6mDh5OYLOptQXh4CoDWdv5qzwuapcv2zHXwclncQ3+HtECZSMQ+c8uNh52nrV16XQFW51nNUZuUT3PX/QvMYOtdjK4/n1pnInH/WkkZKJtJI2hDU7n63xeBqK
  template:
    metadata:
      name: pgadmin-admin-db-secret
      namespace: databases
    type: kubernetes.io/basic-auth
