# Uninstall k3s from all nodes
- name: Uninstall k3s from worker nodes
  hosts: worker_nodes
  become: yes
  tasks:
    - name: Check if k3s agent uninstall script exists
      stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: agent_uninstall_script

    - name: Uninstall k3s agent
      command: /usr/local/bin/k3s-agent-uninstall.sh
      when: agent_uninstall_script.stat.exists

- name: Uninstall k3s from control plane
  hosts: control_plane
  become: yes
  tasks:
    - name: Check if k3s uninstall script exists
      stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: uninstall_script

    - name: Uninstall k3s
      command: /usr/local/bin/k3s-uninstall.sh
      when: uninstall_script.stat.exists
