apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secret
  namespace: home-assistant
spec:
  encryptedData:
    token: AgAOIs3VUvB2+00MWaaQxtA9C8ePuPSld2hUfBzrk7GXz/UR4GV0LXBqFClI7S9066zbquWtK91O/FJbC1k6rBMPHDPJzZVRAZipdpkkQr+7lCotmagkeMVNL9fwWtButEuYu4MUItKLsQ92tBn5vTsrgSi5RyIqoZmeAIRGTscihYL4vFmu43rZ8YMlkzGHG/JSlIxRAENXeMwMoGZ5lG86NscBY5EVFeDXFCeru95kI/z7aFLzZk8SyxW7pW9lK/mLIyLmXMsyWDbfqSfLCtqGFoRsdREGGRcZusBFzg1+Kjv4s+iFAif8L+otD17Yd+OyOYVWsKR/g46nlYEutPp9/wlZI7Ca2U5XdyBFZizzzcUE+J939y86y61/FAdJ0AI0RNTKusqXG7JxR9cdqtgqNpwlE0nIDRaDhCWcKWUhjKspZMq43Bf8HzsOgefRaT/d1eZwYzW0NvRkiF0ZcNZFIPEddp/ggzEACrqfLWObizguWQpz/CnCApKQoBaaPG9h4IlRbVnKDWVKvjQBgnjaHv9ez9JHgmWvofwtuFkMa8zxeCOggINkXr77mEf6E8lWyryf0LbKv3UGrHlKKU64s89GjMkBIb0OQMcRU6cph7185x69fYDkVncKbyB7YoKwMY438vxtmkanZHAx5Ekg9XlrJyPDDrWIlmzC3qED2MJUs5gcLbX6ifDNPjS674g9nMRvLcJReLd4wnbm6GMADQwrS8J90NGm8YDR6LukopigCn9eYj2r1xDj2as8Qr9Y2pASvm5vovcW3dyYd8FLLrE7R0bS5IFW4tNzfompXnMKjwjc6WaKWSmLog0thuYJGwk0TMz9eW3P+lDWutGwZGEXodxwOGsoOEiY5vliYUrFzgs5p6etjjW8YesKmUNJF3ZvXug6zvhmCqKvQwhXst/Lcn3X3j33dtD1vfarmh8MPXu6dA8=
  template:
    metadata:
      name: ha-mcp-secret
      namespace: home-assistant
    type: Opaque
