apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-mcp-secret
  namespace: home-assistant
spec:
  encryptedData:
    token: AgAAGbFvL5gs2P0yin9A3dOVxdlrHP+DTXSDamlQkCik5LGWOcoeOXZ96Av/wfn1nF84OZ7RZ39SHQK9AysW85wldWyJtuNPY9YxInNHwI1A7AQSgNsy9pgqZrwdtSQEpM2lU3gcIj3zvh+jxtlmcsZ/3zTVqrbifAHIwT7q+kJW2XGVR9cbduVn28OfXlkDqVIyW36JHEXTdrHupqIaE256ATIYkDBAC6tgPGU7eDlkeXhy5z0Y0sKeOnbPc3iPv+2aJx7E2stfbPMiAdFB23MOeApXRke1eI6eZPY+LNWE4K3KMKYwPpbJjVBZL01cxzzzwnt1halm2pM5ErFHoKlS/I6QAAxrO/z2EVjn6lg55EKEMuDPopc6+d4Fpzd1W1AOihLCOHtvxEXVSVHfeHg3UR7WeGVJzeZMaUY2SFK6Z5lNf8JK1oZXSFlYig9nmDs1XFF8g4GNY2U2O1Di+TNj/PvVDfnlipIYwff2YgCL1ZQvkd9xb4R8I/pP7zcLeqbQUZ/tkZv46lo8h7abKNdkd0ftUd8JfpD3jJNnlz0Yx5Sq8+NjnIuFaIhlESYSafyNikw4AWdWXK/xscT+MtAVJw6D1jZlwi1lFup3P+d0MtXnt79mYQ4Z3cIpJdqqRsmkgX44aWsJ+LpYRRQ/mYAyDOUxWg+5O+EVqjWHiWrS4Tfdvep4b0Kom8rahoAEGwqeRep33wWQB/1expkFCNS1ESgwj7tu1KsWnP2oG/wM5oJNNmKpN6xhFCSBzCI+bfHczpc+F0HNGGXCyqGD9Fq9zi729oJMn33lWhV+Dx8IMLfsIq+kPDqg79nrGoVjcSJIUebWvh2pi5DsfBpujl09v8Xvhk9JIH39BAbJmy1pJDNqxJpo4mO1Jv3PqyXH7uXhaJ5AstLxB7+ZjO6aRcqBfsR6GDR0TEuuA8y+Vzs/NLIa/H4XsSw=
  template:
    metadata:
      name: home-assistant-mcp-secret
      namespace: home-assistant
    type: Opaque
