apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pi-bot

resources:
  - serviceaccount.yaml
  - sealed-secrets.yaml
  - pvc-home.yaml
  - pvc-workspace.yaml
  - deployment.yaml
