apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-token
  namespace: pi-bot
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgCbQHPtapcM5wsg5BDQnLJ4MetlkAeJ4hkzfB2hKXtr9/6T8AtB93iH9PtTw7bMNFe5o47QHnw48W9bxx3dItVtMMDyVrU6FIXWwKXJucjXLDiRA9j84b2uIELr/mkFuCu7ryD1Rs0+l2UJBmcTuyB15cvejzfuMceNxD6thsRMufWNNSLP91bWK+Qwkk76WMI9ysNekOnB12YF2+YatK6U6cWLndn3ndydvgUn04s1HHmA9LKfGzEi+p8zJj3pfNctV9aHo3C7PlPfW705KZ7suSQi9xwqlkcWEFIq6CaDuVWQ+jqi8xC6CEdY02ofwdxvuLJXVmsV1Q+ZkDNvBskQC/SOlHsncTgTL9OB74pkqC1TLJ3G7fbNKuvt+2vT57EVo+c+8Nlm1b5cniRBFDZlC9RPrbwkzoGZfUY8ah3y6/pAHeArRJaGOQcL3UHVo2x2xGv5ChrUBZGyT5uj+lJ5UzGxTDNMKCnPYrL5bFbpSvcEqtM9JAA8y7S4aMfiRqPBaYyil9nqipdzw3kZGBag1JCi561T4WyRLhdbBS5bp7WkDzryrTnCvJJDb4wGS0iZ2CoZg2ODu5+U3JzbXd8AN+rvzKNUNMj17kHm9OeL2RwH2NRkFCcEZCQBK6+vUzRADIdbn56l/9ZuxO3TDhIrYwCXq/Uj5UTJcXkRnmAXaTHJUhynnP70Iz6wRAZattRA6cOEeOD8hdVcZ1kiNtg7JzsJrRVDKH0h6yed8xyh16Y+vW3XksZfrK1lUFsv
  template:
    metadata:
      name: telegram-bot-token
      namespace: pi-bot
