apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-token
  namespace: pi-bot
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: telegram-bot-token
      namespace: pi-bot
    type: Opaque
