apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

# Helm chart for Immich
helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    version: 0.13.1
    releaseName: immich
    valuesFile: immich-values.yaml

resources:
  - postgres/cluster.yaml
  - postgres/objectstore.yaml
  - postgres/scheduled-backup.yaml
  - postgres/s3-sealed-secrets.yaml
  - postgres/app-sealed-secrets.yaml
  - immich-volumes.yaml
  - sealed-secrets.yaml
