---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgBeTHQBz+CE+Ar5fz56TAu9+f5FPpz8/TJLlXtozARUC6/0qZle1t0cLzWxmhBqQk/OjS9VfptRA4n+Tg6XV6zbTVdREiH8xW/sML3zXdOMLiYerA9A0gDdGduDAqygN1mDs7A/iUgGfLYPYlLymesaDq05oVfoQrt9dIbklUCRen7kuoYfp9l7I81SKYBVk+oEwnmU7QucNtodFOpTojv5tKs2OQ45x60e3aYOhhRp2ugxRgvOOX87M57+P75H8jmLMxE8QkdDaK0CB5M1StB5LwZd0uODsFIWyahvhVh+Lcp38eNA352g0o43qtGubaMwAfZSmwRNBNOo/tYeS3KS8aiL5IdMvjF7r+/Eb0z9e4yW5kIadx55FGY6ZvNLqLro5SfWLRpfLLIHXekox7xLgwt0N5bEIpX6Maqv4l1DY69BCVdxqems8TXvRd6em4GL+mAemGesR5t6jYhcrD8FFNPArkAphYK6IJNU7CGG2JwIojbtsvQxvLl8u7I+iDZyqP5bmiZTFDTcUiVutb20galcPn7FpMmQBUkINfq1fCeT/IMBNgVY1lrilTOcu1k496po+k97jNKkeaFb8w8ya4faf5xjTKckKPCv8c/85EpGfLh33Q4DNlIVLQvyr3BzZEOE/GE5eykwTVDR3KeOG+YJQlpeeSspm/gnHRJ9t3qdHRpYint3ao0tz+5aXeGHDq+IBpYE/yFfBklnrcIq7mSnl6nmFik7AnJtVi4JBf1FFfALmkERIi/yGcExCXvI6IN4rcU/hEAdhwRkXShL0OCixbAzdC04qDHaqGV42TT2TLzPzOeEXjuzmYCQIdZHrlCKd1H38r0ro9V/gNm6PvsaWqq4W5BcvyrTgdNXBGhrHG7bRNmF1ZKTNe4hoMGDffwKRenqxeQGAG9U2Xc2LW8SMxESLY7lT1i83YyGuvdyi1TcsQ6wKeSqJGReZ++44NFWZ9HWrvej6JnxvX8hzf/mex0s/UvRWRtesXeFZsfpBU/7l0hh+/L6ncNvHrx8XphZ8hatsHu1CVqyTVNGLvNcFQKkGVHKhrspdHQY2/K9xl5ruAGMQcJGDkL5yCKxnDntSHJ/R2ExehFtVMLlNngnAqhzFgLReaodJ3xCjVNVqTtE3JKJ2by+IGayE/36GZi5uIAuYlbc7jl0KtQp1cJtpuVePHCGC2vJskmO5SC+YhaAiR+/n/ufXs8F2bpgybrGKYdjV6d4ltVSFp14NhrqudtxEDAIpWnvTIwq6CWynOP2oYQGUSBQxAm1ewT3kejklrxL173Zo71YpEcbgTu7sqzdOQ6vVOlAVqnvNOnq+jejoKIxRTi844rZDtOFhMufMOPzP/MzpRtfKqtb+HKUwQ==
  template:
    metadata:
      name: immich-config
      namespace: immich
    type: Opaque
