---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgAbvqTtQLuMdFaRqtttZc7hzfCTuJ4NTte6V09PZY93ytrO6mBIgpc89uoHSWEZM8gLkNhlYXc/zLtgakNv1rsWasBnyjelW5NxuSjzHB9bt8x276ZfPhBV/a4QPwVTsAmeTxjhzbhAF500IyH6fPQv5dsI+4tA8HTdvcPCGi28o3qrqO0G6bVBgO0M+uYfjcPKIZ8pYPsmT8qXqJh5znjvpFZdmaT99S+psHZJupk/cWKsNLKFsFeGe02fmR1napFBt/1ibvPepcnKAG9o2tHwA/plEZufwuUkSj4lkKV3OPEVQqn8Vm0lFFqq8hT5Ln/XXvpktOTBiSb1wLTvXAR9SwqffxywSchNrdDUPGsBqMsyRaQlWYZJ0SuDAwCK2sYOBHxwo4Pez/OmlfY/eQdLSwmhttXckjp38tbuf8542a5F/3vxR2eXYxf7XloZW0S+KwnacihktnEbBfAFDJiM9aPbJJgsUa9MH8eVMh4M0QTfsknItq36lggd+aL4m9Qk5+P7d6sYOltJNJW/Ib7mXuOUg848henS2zw+CoTO8X24ehkpN+OvXj8e4rgUTCr8znDx3nvAGoDotW7ANr6aDUETE3xFvS+Bs7WhYpOO0B13gVuzb4PhsDglGJj0L5sME6mk5XMIElqBOla30aPd+2WzRS2hd99YUcpQfOzZkj2E846TEarv6Bl8ZzHocJ2tVO7J8dEOgec19Lp+fL9OTogw0oY8+u2yQMEXlDoUPv6wrtlIaiwGdtvZxF/AA24DFAPSJqAlrk9jc81LtEbLS3bcf7EAhtAovzwkSTCc5mxhrmRU7XysWWeoxEC2fHikvVRKhOXGsCrPUFXgVqj1dBSJ+nyRH6QI6kGLQQrvPLpQyYJponSLabixHU+KL9wBoeD4t/ZJoy5vJQNOG2YTJy0C1AOwQtzCgqQowjvS4ADx5xjO11JHqhcf4XSTuFbx/o8PHcYAGV2/Fk4DLVB9nASH0ZOBbPFRXvbhVpNuCIa79W/1go2xOVPVU36ypHn6d5k551j81E/Tl4PGyfltgZxSFBi6lBMI8IYEg/k/sSo0PyL+HKgr9tbKf5GLoZBqRTE23cdhXlkv2dSVXGRQb4qbjmvUj75in9Dfohvlaiv5g0BVQE5QrNUFnZggQ9SowhShzaEQ4AW6Mm69Hz/tpvVZCCtP9/KUeoPAj5xXHarcGNkmamatw6JwvAYbULcXTcebCY1/35W7x6L83lPC7E8WD9/gCQgXIb8x5NdS0CfkAUhu3lyZSiLdiC4go6onsln37t4JfxXcSbVSwy182ig8lbPJ27jV7TZfAXTK/y3YKRsuAt/GVZNDNjExqfLilslgAj+lq6akYYH5Px3NlTC2pl9An/49TMF1Ld/8iPPp5xlVj+aj3aOE7H6Ky3E6JEomXxsfDJAuqtZuO6PFDQMc53J0qJiZIIQ/7LETUn+SXzDni54OLmVY2bLkVeqA21aQVyHuvKGOLruHH1tLh7jYGRctrwqhTrqP6dDBT6XIMknvp1J3AfKo
  template:
    metadata:
      name: immich-config
      namespace: immich
    type: Opaque
