victoria-metrics-k8s-stack:
  grafana:
    enabled: true
    envFromSecret: grafana-oauth-secret
    grafana.ini:
      server:
        root_url: https://grafana.mauzlab.de
      auth:
        disable_login_form: false
      auth.generic_oauth:
        enabled: true
        name: Authentik
        allow_sign_up: true
        client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
        client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
        scopes: openid email profile
        auth_url: https://auth.mauzlab.de/application/o/authorize/
        token_url: https://auth.mauzlab.de/application/o/token/
        api_url: https://auth.mauzlab.de/application/o/userinfo/
        role_attribute_path: contains(groups[*], 'homelab-admins') && 'Admin' || 'Viewer'
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - grafana.mauzlab.de
  # Disable the complex cluster version
  vmcluster:
    enabled: false

  # Enable the efficient single binary version
  vmsingle:
    enabled: true
    spec:
      retentionPeriod: "30d"
      resources:
        limits:
          memory: "1024Mi"
      storage:
        storageClassName: local-path
        resources:
          requests:
            storage: "5Gi"

  # Optional: Disable HA/Replica settings for Alertmanager to save RAM
  alertmanager:
    enabled: true
    spec:
      replicaCount: 1
