apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paseo-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: paseo
    namespace: paseo
