---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-api-key
  namespace: klaus
spec:
  encryptedData:
    PASEO_API_KEY: AgCKcoNpsTbaSPThlfxDwdJ8K/GyLDOc0uLQcbygVnF59WyVSlqHPDfizCAM/VS1ppVemu9VtGpWMZVcqyKGGUo3/xfOE2vomvT2Qh8xNPpNxf5aAM58TC09Pp459ca1/x+fGHYmTWCIb6CCjbxhPDSTDO7ILALrSAGAV0Gfhp2OKhmXYaRPaKlLycA1vafhpsgAfKh/6qpyWJg3if9Q9GmukD3XJXI4ftvovQuqOP6zkQduB4KFiMwEwmmSmeSfMYlpCOiAVp63rhfbq5bh/W8ogF7r+NQdxkmOwMufLm7eG3iOPM5qIyH7dpMyT7uD5agPEAYzObZjwqQoi30KQMHgxm71oVCxT5lDAnk2WiRKJznSdxQ20nh2xcPrDqlKRDnYYcHzL7MgtXVYnh9mnzFVJl1iVw/UE4dwAWT9WrUV1hULUoVDPvz+1G6Eyqx7PbohPdHjRY/X+n7Cj5I37ZPw52OgzkE0iyaTcDfpxanpcVnz7vCwBzJL+l4mDM5ZWlzCsZTMSVOOgz9nDAgD5FDaEPVSCRgtEtRyhIBqHB0To64rMIaqFbmNaJj6BJEjWBcVypFNvUQtwnyP+zmTxIEJj/91hSkV3j5EhHqgyBNQADiY+Q1oF0ezqQ3tcMcQGNoBTovXFgtNHCfb00k4PRsO+KgnUibzFb9TvKQZylFmydkcCtZUcvc419hip4jMmtKnmRI2kZL3yqbqlDlbZQ1JdtsmUqp2m4qAKDzx719A4QfHK1pr4WTnetU34yKIPYjNBk8wqjAq/S7TKxye34Re
  template:
    metadata:
      name: paseo-api-key
      namespace: klaus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-token
  namespace: klaus
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgAb/R1TWZ6g2ho74ABtyfGxqwB8JEEpewJrIm559e+LhZ3QK/ShdKukxVFTUWerbaXr0RfolhRT7gF/8Jk6O0L++cEXtEXWsXwcaLOBTGasY0mtavSVCWh7VJE9AEIfduk/Dl5WTAXqYuUbx8qY/IJtcnQv7ZAztk59qgDsv7RxRk19YvWu8Ef31laoH3zY8JDErHYOGXxXDWu46t/KioEE9N09bVcES01XKqKh+xhDD/1GnjGQgpuo75xrOsDI4eRBx18PaRp6VzRRSXaaIueil85VsLQ2WBX/Ophbqr48HtT/VS0PTwHcMywtnuyk5WUA2nkZPb6KvLsK1sa9cQKp6bPjuVIK00oli0ymwlL7CKTas/VjhLJWSwfb7FNaf5LHHE51BOKcgducbqiCzbl7z/IWM41CNRyYevxwf863aJqO7FztEZ9sue3IPQUo3cdaG/zG6Fw7MUXX9V5t0v8r5lJz2e0TuVvPufxYRrgMuSJVRpMWMtgylUUXDDBjKTmXjC3qS1H/+MhdNdip+ENAYvdMGj5Io14f9jsPfrJenFkw6BAmEi9uXF1jRzvRAVlzdPM2JV6s/uFkQ7y4a7mYjUu4vJndh8knqzq6tYSv/F/F29+9YPnwE6fH/eFkxm+JSvOBFgJHKG0b57t/TjiULLTa5B9Q+GxKI4YFllIe3dcUqXsL2so4Ohw1K8AEK+9I/Q7OoagbUR7y5omW/wnlspZU096TzTaQhZiSEZIFMQXJvjU52nJAD8M6JfOp
  template:
    metadata:
      name: telegram-bot-token
      namespace: klaus
