---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaneo-api-key
  namespace: klaus
spec:
  encryptedData:
    KANEO_API_KEY: AgAGNd39tSqrEEOFALM+1e7kr7ZNG0wALGmnf+R7Hw/bTsaY1cETH8YlTi+XNo5SRe1sNCQ5kVVsodv7CivUEaB+hnvtg274Pt2gT51fp36eG1Mwhcs2zkX8VyMJ+dOUUBNGojn0emnYKr+V5Llel7z1RYYcTB9i9BXPO4gtmZfQEw52nEZks1OTccLD3xIYtKEd8IubicXxCteFZrOu4Ypq3fCGEThz/BFraS6KglokT4kBFm4cdBPMurj8t/T+QsqXH0Ak/wCWPkAT+wLlWzNKtKi6FUNP6V8ge5mhFFMC3f98nfrjotkJieYEcAahF25lBdytHW1hNyF7ysOVx5twExVnSthDwi1YWb/NCvqPH4s169wP/l9lcEMHxRxWTvvwt/R2/WJciOKkQSpFe00jxyai3vyBMwG1YkzrN/+lV3r+tE8cJPjBJVdbTRDNeR9UdEmsLVpdi8oZU8O0ksH3ehEs/FoDOwyQlXYx6qMtCOgRqqroo7XsIWnPbMcpL9MLpH2K7A8e6xzXfThREtup0tw7eiBl0AEAYe4msSpGKelHFurAiWugmlM/Vkv47E9R/KSfLK9PN4DatD7rosUIyNOXK26i4Djbva33mdHFsWRpT4MErzie5zhLXakBw3g4nM/2yRC4xxTOavjSOk+RWf1hIWg4AvKSwMj0D6fHVtEfifuLI2gOyENN9uqTE2TZY+FVh2DbD0b1TAE61BAfIJswolj/yfu3SIKJb3VejpEXnSUqx0nOtJanurKPjk4MVcfFiBpSIFnkmsC5k3F3
  template:
    metadata:
      name: kaneo-api-key
      namespace: klaus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-token
  namespace: klaus
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgAb/R1TWZ6g2ho74ABtyfGxqwB8JEEpewJrIm559e+LhZ3QK/ShdKukxVFTUWerbaXr0RfolhRT7gF/8Jk6O0L++cEXtEXWsXwcaLOBTGasY0mtavSVCWh7VJE9AEIfduk/Dl5WTAXqYuUbx8qY/IJtcnQv7ZAztk59qgDsv7RxRk19YvWu8Ef31laoH3zY8JDErHYOGXxXDWu46t/KioEE9N09bVcES01XKqKh+xhDD/1GnjGQgpuo75xrOsDI4eRBx18PaRp6VzRRSXaaIueil85VsLQ2WBX/Ophbqr48HtT/VS0PTwHcMywtnuyk5WUA2nkZPb6KvLsK1sa9cQKp6bPjuVIK00oli0ymwlL7CKTas/VjhLJWSwfb7FNaf5LHHE51BOKcgducbqiCzbl7z/IWM41CNRyYevxwf863aJqO7FztEZ9sue3IPQUo3cdaG/zG6Fw7MUXX9V5t0v8r5lJz2e0TuVvPufxYRrgMuSJVRpMWMtgylUUXDDBjKTmXjC3qS1H/+MhdNdip+ENAYvdMGj5Io14f9jsPfrJenFkw6BAmEi9uXF1jRzvRAVlzdPM2JV6s/uFkQ7y4a7mYjUu4vJndh8knqzq6tYSv/F/F29+9YPnwE6fH/eFkxm+JSvOBFgJHKG0b57t/TjiULLTa5B9Q+GxKI4YFllIe3dcUqXsL2so4Ohw1K8AEK+9I/Q7OoagbUR7y5omW/wnlspZU096TzTaQhZiSEZIFMQXJvjU52nJAD8M6JfOp
  template:
    metadata:
      name: telegram-bot-token
      namespace: klaus

---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-api-key
  namespace: klaus
spec:
  encryptedData:
    MEALIE_API_KEY: AgAgHvxbuA1pFXyDjewQG00RvrGr1aVQeRVxlx9UtLbeZP1Wy0Kq7Txds/5+1tblp23AMsK7lI2/tK3IdMlQ4PUnOSPjrs3nh6y9lGP3Mp0AdtTR8APMaWt5vdKEuIAgSIauRgpC5mLdPE08708C0thcq1TYRwSnZxRAMWoaN9Ix4zUErhA9o64ufEs6idjTCKKUO+7p6WBFdQ2HdM5mQx2jkAwvoQTfgyZrHhzPNJQ/2Ee4NHKkHcVzkONVrD8dhfKanJwPX+f3uaDXsWjzbsp7LazPmwHOwRYnV15nTCKULNogYzghY+ZvDEQW5iPuwzIqPku2TCqv1VEOAux/+nIxebFnqnFo3hbHZyhGWj+JfiaIx4W/VV+KlVLVwWTzdgywju8nJzo3wuZnEITFyBPoe8voIyg2ZWuvz/ewjAM2Tz+SkQlcLfpw8+11/qnFfLLmq/VoW3diwcmrYmvctkDiInbd+Klr47pt2PQgg6ntH2g5hEaqY94tOygGu6uevRW6ahnxUf/54/GVeryrIefw2MQwyyCuFWap44ANjrPOY1mFE/IYhMCOypnmoMRRgp96mBw/J9Vxlho5cVAFqy69pXJXPQZHCfL0IxgrSDKBaB51IZI5nGfIWKonzBddR8OQLzosRbdINXHnso2mWDmeGVJqogDBTd52hyeo7ey1V/Ok+C0P/bX6IzP+lp/veclWSzpJaLivLPRWf/0puJ65WctOtaivUypn4Hsdg+0zRVJNY0GtCauXidIHhXWy4VfIkWAY1amnetRCgh8oHhn94RncsrBQ6kGwru0KCEWiVkXp2FP4cwsMN9Y9OvFjvwQSrlLsFCe9Nksnts/jMwwVcybgdS7R4bcdwpRaPIXmU97a7eOc6Me1atv5FFr5pHtCfLqnE+DbAd3HtDml1+AZvUcF73aL1ri0EFeBBsmxq/F6BjOBjZao10UoG3cnZ6logBacmOYqlxoA/NB4sklsdt81q2/WcNSdpORoo1evC8BInhWA/YTtiAIao0iFow4iosBXBcaO/EGeoObysMaTMWgwCFcLIaHnUZ3BUgBAwEpOgzYmKnxiF6KYhH6zXa0K17+BPQCd
  template:
    metadata:
      name: mealie-api-key
      namespace: klaus
