authentik:
  existingSecret:
    secretName: authentik-config

global:
  env:
    - name: AUTHENTIK_WEB__BASE_URL
      value: "https://auth.mauzlab.de"

# disable builtin postgres
postgresql:
  enabled: false

server:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

worker:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
